# fly.toml app configuration file generated for fly-nix-test on 2025-01-10T13:13:38-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-nix-test'
primary_region = 'den'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0

  [[services.ports]]
    port = 8080

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 2
